#!/bin/bash

C_ARCH="32"                     # generate 32-bit x86 code
LD_ARCH="elf_i386"              # generate a i386 compatible ELF program file
KERNEL_ADDRESS="0x1000"         # where to load our kernel
KERNEL_IMAGE="os-image"         # what our kernel image will be called

echo "Building 32-bit kernel image"

gcc -m$C_ARCH -ffreestanding -c kernel_main.c -o kernel_main.o
ld -m$LD_ARCH -o kernel_main.bin -Ttext ${KERNEL_ADDRESS} -e main --oformat binary kernel_main.o 
as -o boot_with_switch.o boot_with_switch.s
ld -o boot_with_switch.bin --oformat binary -Ttext 0x7c00 -e _start boot_with_switch.o
cat boot_with_switch.bin kernel_main.bin > $KERNEL_IMAGE

echo "Kernel Image: ${KERNEL_IMAGE}"
qemu-system-x86_64 $KERNEL_IMAGE
